export default {
  // 整个歌单
  songList: [],
  // 当前播放音乐的下标
  index: 0,
  // 当前播放音乐的信息
  audio: {
    // mp3资源
    audioSrc: '',
    // 初始化图片
    audioImg: 'http://m.kugou.com/v3/static/images/index/logo_kugou.png',
    // 歌名
    title: '',
    // 歌手名
    singerName: '',
    // 文件名
    fileName: '',
    // 当前播放时间
    currentLength: 0,
    // 歌曲总时长
    songLength: 0,
    // 当前播放时间发生改变
    currentFlag: false,
    // 歌词
    lrc: ''
  },
  // 是否显示底部播放栏
  showPlayBol: false,
  // 是否隐藏底部播放栏
  hideBol: false,
  // 是否播放音乐
  isPlay: true,
  // 头部子组件是否显示导航
  isNav: true,
  // 头部名字
  headName: '',
  // 背景颜色
  bgcolor: '-webkit-linear-gradient(top,rgba(0,0,0,.6),transparent)',
  // 显示歌词页
  showDetailBol: false
}
